# Generated by Django 5.0.4 on 2024-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("READ", "Read"), ("UNREAD", "Unread")],
                default="UNREAD",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
