# Generated by Django 5.0.4 on 2024-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_alter_orderitem_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebInFo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_pdf",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="webinfor/company",
                        verbose_name="Company PDF",
                    ),
                ),
                (
                    "employee_pdf",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="webinfor/employee",
                        verbose_name="Employee PDF",
                    ),
                ),
            ],
        ),
    ]
