# Generated by Django 5.0.4 on 2024-05-07 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.PositiveSmallIntegerField()),
                ("major", models.CharField(max_length=100)),
                ("skill", models.TextField()),
                ("image", models.FileField(upload_to="resume", verbose_name="image")),
                (
                    "resume_image",
                    models.FileField(upload_to="resume", verbose_name="Resume image"),
                ),
                ("is_recommend", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
